language: python

python:
  - "2.7"

env:
  - VERSION="8.0" ODOO_REPO="odoo/odoo"
  - VERSION="8.0" ODOO_REPO="OCA/OCB"

virtualenv:
  system_site_packages: true

install:
  - pip install xlwt
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly ${VERSION}

script:
  - travis_run_tests ${VERSION}

after_success:
  coveralls
