sudo: false
cache: pip

addons:
  apt:
  # only add the two lines below if you need wkhtmltopdf for your tests
    sources:
      - pov-wkhtmltopdf
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow
      - python-simplejson
      - pdftk
      - libreoffice
      - wkhtmltopdf  # only add if needed and check the before_install section below
  postgresql: "9.3"

# set up an X server to run wkhtmltopdf.
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

language: python

python:
  - "3.5"

env:
  global:
  - VERSION="11.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"
  - TRANSIFEX_USER='transbot@odoo-community.org'
  - secure: NUsXwVrMntcqge1ozKW+DSkP7dq+Rla6JVvFF2c89/g+zJaIqQRi8EQBLoqNwCdMk+rjpQeZt/JPELjH+EzPcmGddhDxOgVB3nUT9LvFXGCHF+NjmHXqyba4tuc7BnpG1WDD+rSlxVCt1aIjNIhhaZ4ic0rCWpKNYu/yFTsmChc=
  matrix:
  - LINT_CHECK="1"
  - TRANSIFEX="1"
  - TESTS="1" ODOO_REPO="OCA/OCB" OPTIONS="--test-report-directory=/tmp"
  - TESTS="1" ODOO_REPO="odoo/odoo" OPTIONS="--test-report-directory=/tmp"


install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - export WKHTMLTOPDF_VERSION=0.12.4
  - travis_install_nightly
  - pip install PyPDF2  # needed for report_qweb_pdf_watermark 

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
